//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cockpit_NextGenMVC.BAL_User_Mgmt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VW_USERS", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class VW_USERS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COUNTRYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FULLNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NTLOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROFILE_PICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROLE_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAP_User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPERREGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEAM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVE {
            get {
                return this.ACTIVEField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVEField, value) != true)) {
                    this.ACTIVEField = value;
                    this.RaisePropertyChanged("ACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COUNTRY {
            get {
                return this.COUNTRYField;
            }
            set {
                if ((object.ReferenceEquals(this.COUNTRYField, value) != true)) {
                    this.COUNTRYField = value;
                    this.RaisePropertyChanged("COUNTRY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FULLNAME {
            get {
                return this.FULLNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLNAMEField, value) != true)) {
                    this.FULLNAMEField = value;
                    this.RaisePropertyChanged("FULLNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NTLOGIN {
            get {
                return this.NTLOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.NTLOGINField, value) != true)) {
                    this.NTLOGINField = value;
                    this.RaisePropertyChanged("NTLOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROFILE_PIC {
            get {
                return this.PROFILE_PICField;
            }
            set {
                if ((object.ReferenceEquals(this.PROFILE_PICField, value) != true)) {
                    this.PROFILE_PICField = value;
                    this.RaisePropertyChanged("PROFILE_PIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROLE_DESC {
            get {
                return this.ROLE_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLE_DESCField, value) != true)) {
                    this.ROLE_DESCField = value;
                    this.RaisePropertyChanged("ROLE_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAP_User_Name {
            get {
                return this.SAP_User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.SAP_User_NameField, value) != true)) {
                    this.SAP_User_NameField = value;
                    this.RaisePropertyChanged("SAP_User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPERREGION {
            get {
                return this.SUPERREGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPERREGIONField, value) != true)) {
                    this.SUPERREGIONField = value;
                    this.RaisePropertyChanged("SUPERREGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEAM_NAME {
            get {
                return this.TEAM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.TEAM_NAMEField, value) != true)) {
                    this.TEAM_NAMEField = value;
                    this.RaisePropertyChanged("TEAM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((this.USER_IDField.Equals(value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_USERS", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class TBL_USERS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COUNTRYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FULLNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NTLOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROFILE_PICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ROLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SUBSCRIPTION_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPERREGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TEAM_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTIVE {
            get {
                return this.ACTIVEField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIVEField, value) != true)) {
                    this.ACTIVEField = value;
                    this.RaisePropertyChanged("ACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COUNTRY {
            get {
                return this.COUNTRYField;
            }
            set {
                if ((object.ReferenceEquals(this.COUNTRYField, value) != true)) {
                    this.COUNTRYField = value;
                    this.RaisePropertyChanged("COUNTRY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FULLNAME {
            get {
                return this.FULLNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLNAMEField, value) != true)) {
                    this.FULLNAMEField = value;
                    this.RaisePropertyChanged("FULLNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NTLOGIN {
            get {
                return this.NTLOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.NTLOGINField, value) != true)) {
                    this.NTLOGINField = value;
                    this.RaisePropertyChanged("NTLOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROFILE_PIC {
            get {
                return this.PROFILE_PICField;
            }
            set {
                if ((object.ReferenceEquals(this.PROFILE_PICField, value) != true)) {
                    this.PROFILE_PICField = value;
                    this.RaisePropertyChanged("PROFILE_PIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ROLE_ID {
            get {
                return this.ROLE_IDField;
            }
            set {
                if ((this.ROLE_IDField.Equals(value) != true)) {
                    this.ROLE_IDField = value;
                    this.RaisePropertyChanged("ROLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SUBSCRIPTION_ID {
            get {
                return this.SUBSCRIPTION_IDField;
            }
            set {
                if ((this.SUBSCRIPTION_IDField.Equals(value) != true)) {
                    this.SUBSCRIPTION_IDField = value;
                    this.RaisePropertyChanged("SUBSCRIPTION_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPERREGION {
            get {
                return this.SUPERREGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPERREGIONField, value) != true)) {
                    this.SUPERREGIONField = value;
                    this.RaisePropertyChanged("SUPERREGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TEAM_ID {
            get {
                return this.TEAM_IDField;
            }
            set {
                if ((this.TEAM_IDField.Equals(value) != true)) {
                    this.TEAM_IDField = value;
                    this.RaisePropertyChanged("TEAM_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((this.USER_IDField.Equals(value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Unmapped_Users", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class Tbl_Unmapped_Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Order_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Total_NVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERGROUPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Order_Count {
            get {
                return this.Order_CountField;
            }
            set {
                if ((this.Order_CountField.Equals(value) != true)) {
                    this.Order_CountField = value;
                    this.RaisePropertyChanged("Order_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalUser {
            get {
                return this.TotalUserField;
            }
            set {
                if ((this.TotalUserField.Equals(value) != true)) {
                    this.TotalUserField = value;
                    this.RaisePropertyChanged("TotalUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Total_NV {
            get {
                return this.Total_NVField;
            }
            set {
                if ((this.Total_NVField.Equals(value) != true)) {
                    this.Total_NVField = value;
                    this.RaisePropertyChanged("Total_NV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERGROUP {
            get {
                return this.USERGROUPField;
            }
            set {
                if ((object.ReferenceEquals(this.USERGROUPField, value) != true)) {
                    this.USERGROUPField = value;
                    this.RaisePropertyChanged("USERGROUP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Country_Sorg_Orig", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class Tbl_Country_Sorg_Orig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SorgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sorg {
            get {
                return this.SorgField;
            }
            set {
                if ((object.ReferenceEquals(this.SorgField, value) != true)) {
                    this.SorgField = value;
                    this.RaisePropertyChanged("Sorg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_TEAM_STRUCTURE", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class TBL_TEAM_STRUCTURE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ACTIVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BACKUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BACKUPFROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BACKUPTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BACKUP_COMMENTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPERVISORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TEAM_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEAM_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ACTIVE {
            get {
                return this.ACTIVEField;
            }
            set {
                if ((this.ACTIVEField.Equals(value) != true)) {
                    this.ACTIVEField = value;
                    this.RaisePropertyChanged("ACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BACKUP {
            get {
                return this.BACKUPField;
            }
            set {
                if ((object.ReferenceEquals(this.BACKUPField, value) != true)) {
                    this.BACKUPField = value;
                    this.RaisePropertyChanged("BACKUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BACKUPFROM {
            get {
                return this.BACKUPFROMField;
            }
            set {
                if ((this.BACKUPFROMField.Equals(value) != true)) {
                    this.BACKUPFROMField = value;
                    this.RaisePropertyChanged("BACKUPFROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BACKUPTO {
            get {
                return this.BACKUPTOField;
            }
            set {
                if ((this.BACKUPTOField.Equals(value) != true)) {
                    this.BACKUPTOField = value;
                    this.RaisePropertyChanged("BACKUPTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BACKUP_COMMENTS {
            get {
                return this.BACKUP_COMMENTSField;
            }
            set {
                if ((object.ReferenceEquals(this.BACKUP_COMMENTSField, value) != true)) {
                    this.BACKUP_COMMENTSField = value;
                    this.RaisePropertyChanged("BACKUP_COMMENTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPERVISOR {
            get {
                return this.SUPERVISORField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPERVISORField, value) != true)) {
                    this.SUPERVISORField = value;
                    this.RaisePropertyChanged("SUPERVISOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TEAM_ID {
            get {
                return this.TEAM_IDField;
            }
            set {
                if ((this.TEAM_IDField.Equals(value) != true)) {
                    this.TEAM_IDField = value;
                    this.RaisePropertyChanged("TEAM_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEAM_NAME {
            get {
                return this.TEAM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.TEAM_NAMEField, value) != true)) {
                    this.TEAM_NAMEField = value;
                    this.RaisePropertyChanged("TEAM_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBL_ROLE", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class TBL_ROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROLE_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ROLE_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROLE_DESC {
            get {
                return this.ROLE_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLE_DESCField, value) != true)) {
                    this.ROLE_DESCField = value;
                    this.RaisePropertyChanged("ROLE_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ROLE_ID {
            get {
                return this.ROLE_IDField;
            }
            set {
                if ((this.ROLE_IDField.Equals(value) != true)) {
                    this.ROLE_IDField = value;
                    this.RaisePropertyChanged("ROLE_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Unmapped_Orders_By_Region_Function", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
    [System.SerializableAttribute()]
    public partial class Tbl_Unmapped_Orders_By_Region_Function : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORDER_CREATED_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> Total_NVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORDER_CREATED_BY {
            get {
                return this.ORDER_CREATED_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDER_CREATED_BYField, value) != true)) {
                    this.ORDER_CREATED_BYField = value;
                    this.RaisePropertyChanged("ORDER_CREATED_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((this.OrdersField.Equals(value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Total_NV {
            get {
                return this.Total_NVField;
            }
            set {
                if ((this.Total_NVField.Equals(value) != true)) {
                    this.Total_NVField = value;
                    this.RaisePropertyChanged("Total_NV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BAL_User_Mgmt.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUserDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserDetails(string NtLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserDetails", ReplyAction="http://tempuri.org/IService1/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserDetailsAsync(string NtLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserTeamDetails", ReplyAction="http://tempuri.org/IService1/GetUserTeamDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUserTeamDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserTeamDetails(string TeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserTeamDetails", ReplyAction="http://tempuri.org/IService1/GetUserTeamDetailsResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserTeamDetailsAsync(string TeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegionDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegionDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUserRegionDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserRegionDetails(string RegionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserRegionDetails", ReplyAction="http://tempuri.org/IService1/GetUserRegionDetailsResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserRegionDetailsAsync(string RegionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInActiveUserTeamDetails", ReplyAction="http://tempuri.org/IService1/GetInActiveUserTeamDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetInActiveUserTeamDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetInActiveUserTeamDetails(string TeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInActiveUserTeamDetails", ReplyAction="http://tempuri.org/IService1/GetInActiveUserTeamDetailsResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetInActiveUserTeamDetailsAsync(string TeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterNewUser", ReplyAction="http://tempuri.org/IService1/RegisterNewUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/RegisterNewUserServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        bool RegisterNewUser(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterNewUser", ReplyAction="http://tempuri.org/IService1/RegisterNewUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterNewUserAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/UpdateUserDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        bool UpdateUserDetails(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserDetails", ReplyAction="http://tempuri.org/IService1/UpdateUserDetailsResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserDetailsAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersByRegion", ReplyAction="http://tempuri.org/IService1/GetUsersByRegionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUsersByRegionServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUsersByRegion(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersByRegion", ReplyAction="http://tempuri.org/IService1/GetUsersByRegionResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUsersByRegionAsync(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnMappedUsersByRegion", ReplyAction="http://tempuri.org/IService1/GetUnMappedUsersByRegionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUnMappedUsersByRegionServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Users[] GetUnMappedUsersByRegion(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnMappedUsersByRegion", ReplyAction="http://tempuri.org/IService1/GetUnMappedUsersByRegionResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Users[]> GetUnMappedUsersByRegionAsync(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActiveDeactiveUser", ReplyAction="http://tempuri.org/IService1/ActiveDeactiveUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/ActiveDeactiveUserServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        bool ActiveDeactiveUser(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActiveDeactiveUser", ReplyAction="http://tempuri.org/IService1/ActiveDeactiveUserResponse")]
        System.Threading.Tasks.Task<bool> ActiveDeactiveUserAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountryByRegion", ReplyAction="http://tempuri.org/IService1/GetCountryByRegionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetCountryByRegionServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Country_Sorg_Orig[] GetCountryByRegion(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountryByRegion", ReplyAction="http://tempuri.org/IService1/GetCountryByRegionResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Country_Sorg_Orig[]> GetCountryByRegionAsync(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetManagerByTeamID", ReplyAction="http://tempuri.org/IService1/GetManagerByTeamIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetManagerByTeamIDServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[] GetManagerByTeamID(int TeamID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetManagerByTeamID", ReplyAction="http://tempuri.org/IService1/GetManagerByTeamIDResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[]> GetManagerByTeamIDAsync(int TeamID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleMaster", ReplyAction="http://tempuri.org/IService1/GetRoleMasterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetRoleMasterServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_ROLE[] GetRoleMaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleMaster", ReplyAction="http://tempuri.org/IService1/GetRoleMasterResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_ROLE[]> GetRoleMasterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeamMaster", ReplyAction="http://tempuri.org/IService1/GetTeamMasterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetTeamMasterServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[] GetTeamMaster(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTeamMaster", ReplyAction="http://tempuri.org/IService1/GetTeamMasterResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[]> GetTeamMasterAsync(string Region);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnMappedUsersByRegionFunction", ReplyAction="http://tempuri.org/IService1/GetUnMappedUsersByRegionFunctionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetUnMappedUsersByRegionFunctionServiceExceptionFaul" +
            "t", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Orders_By_Region_Function[] GetUnMappedUsersByRegionFunction(string Region, string BusinessFunction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnMappedUsersByRegionFunction", ReplyAction="http://tempuri.org/IService1/GetUnMappedUsersByRegionFunctionResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Orders_By_Region_Function[]> GetUnMappedUsersByRegionFunctionAsync(string Region, string BusinessFunction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNTLoginBySAPName", ReplyAction="http://tempuri.org/IService1/GetNTLoginBySAPNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/GetNTLoginBySAPNameServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetNTLoginBySAPName(string SAPName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNTLoginBySAPName", ReplyAction="http://tempuri.org/IService1/GetNTLoginBySAPNameResponse")]
        System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetNTLoginBySAPNameAsync(string SAPName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserInSApandBBZTRD", ReplyAction="http://tempuri.org/IService1/UpdateUserInSApandBBZTRDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/UpdateUserInSApandBBZTRDServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        bool UpdateUserInSApandBBZTRD(string OrderOwner, string CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserInSApandBBZTRD", ReplyAction="http://tempuri.org/IService1/UpdateUserInSApandBBZTRDResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserInSApandBBZTRDAsync(string OrderOwner, string CreatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmailIDByName", ReplyAction="http://tempuri.org/IService1/getEmailIDByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Cockpit_NextGenMVC.BAL_User_Mgmt.ServiceException), Action="http://tempuri.org/IService1/getEmailIDByNameServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/BAL_Service_User_Mgmt")]
        string getEmailIDByName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmailIDByName", ReplyAction="http://tempuri.org/IService1/getEmailIDByNameResponse")]
        System.Threading.Tasks.Task<string> getEmailIDByNameAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Cockpit_NextGenMVC.BAL_User_Mgmt.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Cockpit_NextGenMVC.BAL_User_Mgmt.IService1>, Cockpit_NextGenMVC.BAL_User_Mgmt.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserDetails(string NtLogin) {
            return base.Channel.GetUserDetails(NtLogin);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserDetailsAsync(string NtLogin) {
            return base.Channel.GetUserDetailsAsync(NtLogin);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserTeamDetails(string TeamName) {
            return base.Channel.GetUserTeamDetails(TeamName);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserTeamDetailsAsync(string TeamName) {
            return base.Channel.GetUserTeamDetailsAsync(TeamName);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUserRegionDetails(string RegionName) {
            return base.Channel.GetUserRegionDetails(RegionName);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUserRegionDetailsAsync(string RegionName) {
            return base.Channel.GetUserRegionDetailsAsync(RegionName);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetInActiveUserTeamDetails(string TeamName) {
            return base.Channel.GetInActiveUserTeamDetails(TeamName);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetInActiveUserTeamDetailsAsync(string TeamName) {
            return base.Channel.GetInActiveUserTeamDetailsAsync(TeamName);
        }
        
        public bool RegisterNewUser(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.RegisterNewUser(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterNewUserAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.RegisterNewUserAsync(oUser);
        }
        
        public bool UpdateUserDetails(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.UpdateUserDetails(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserDetailsAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.UpdateUserDetailsAsync(oUser);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetUsersByRegion(string Region) {
            return base.Channel.GetUsersByRegion(Region);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetUsersByRegionAsync(string Region) {
            return base.Channel.GetUsersByRegionAsync(Region);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Users[] GetUnMappedUsersByRegion(string Region) {
            return base.Channel.GetUnMappedUsersByRegion(Region);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Users[]> GetUnMappedUsersByRegionAsync(string Region) {
            return base.Channel.GetUnMappedUsersByRegionAsync(Region);
        }
        
        public bool ActiveDeactiveUser(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.ActiveDeactiveUser(oUser);
        }
        
        public System.Threading.Tasks.Task<bool> ActiveDeactiveUserAsync(Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_USERS oUser) {
            return base.Channel.ActiveDeactiveUserAsync(oUser);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Country_Sorg_Orig[] GetCountryByRegion(string Region) {
            return base.Channel.GetCountryByRegion(Region);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Country_Sorg_Orig[]> GetCountryByRegionAsync(string Region) {
            return base.Channel.GetCountryByRegionAsync(Region);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[] GetManagerByTeamID(int TeamID) {
            return base.Channel.GetManagerByTeamID(TeamID);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[]> GetManagerByTeamIDAsync(int TeamID) {
            return base.Channel.GetManagerByTeamIDAsync(TeamID);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_ROLE[] GetRoleMaster() {
            return base.Channel.GetRoleMaster();
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_ROLE[]> GetRoleMasterAsync() {
            return base.Channel.GetRoleMasterAsync();
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[] GetTeamMaster(string Region) {
            return base.Channel.GetTeamMaster(Region);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.TBL_TEAM_STRUCTURE[]> GetTeamMasterAsync(string Region) {
            return base.Channel.GetTeamMasterAsync(Region);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Orders_By_Region_Function[] GetUnMappedUsersByRegionFunction(string Region, string BusinessFunction) {
            return base.Channel.GetUnMappedUsersByRegionFunction(Region, BusinessFunction);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.Tbl_Unmapped_Orders_By_Region_Function[]> GetUnMappedUsersByRegionFunctionAsync(string Region, string BusinessFunction) {
            return base.Channel.GetUnMappedUsersByRegionFunctionAsync(Region, BusinessFunction);
        }
        
        public Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[] GetNTLoginBySAPName(string SAPName) {
            return base.Channel.GetNTLoginBySAPName(SAPName);
        }
        
        public System.Threading.Tasks.Task<Cockpit_NextGenMVC.BAL_User_Mgmt.VW_USERS[]> GetNTLoginBySAPNameAsync(string SAPName) {
            return base.Channel.GetNTLoginBySAPNameAsync(SAPName);
        }
        
        public bool UpdateUserInSApandBBZTRD(string OrderOwner, string CreatedBy) {
            return base.Channel.UpdateUserInSApandBBZTRD(OrderOwner, CreatedBy);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserInSApandBBZTRDAsync(string OrderOwner, string CreatedBy) {
            return base.Channel.UpdateUserInSApandBBZTRDAsync(OrderOwner, CreatedBy);
        }
        
        public string getEmailIDByName(string Name) {
            return base.Channel.getEmailIDByName(Name);
        }
        
        public System.Threading.Tasks.Task<string> getEmailIDByNameAsync(string Name) {
            return base.Channel.getEmailIDByNameAsync(Name);
        }
    }
}
