//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Customers
    {
        public string REGION { get; set; }
        public string SOLD_TO_COUNTRY { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string SOLD_TO_PARTY { get; set; }
        public string SOLD_TO_PARTY_NAME { get; set; }
        public string SHIP_TO_PARTY { get; set; }
        public string SHIP_TO_PARTY_NAME { get; set; }
        public string ZU_ACCOUNT_NAME { get; set; }
        public string ZU_COUNTRY { get; set; }
        public string PAYMENT_TYPE { get; set; }
    }
}
