//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Sales_Force
    {
        public string REGION { get; set; }
        public string QUOTA_SF { get; set; }
        public string FE_FE_DESC { get; set; }
        public string SRTATTR_AREA_MGR_NME { get; set; }
        public string SRTATTR_DISTRICT_MGR_NME { get; set; }
    }
}
