//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Business_Master
    {
        public string BUSINESS_GROUP { get; set; }
        public string REGION { get; set; }
        public string DIVISION { get; set; }
        public string SALES_ORG { get; set; }
        public string PRODUCT_LINE { get; set; }
    }
}
