//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETL_SAP_User_Updates
    {
        public string USERNAME { get; set; }
        public string COMPLETENAME { get; set; }
        public string EMAIL { get; set; }
        public string USERGROUP { get; set; }
    }
}
