//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNI_Excel_View
    {
        public string REGION { get; set; }
        public double SALES_ORDERNO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string SALES_ORG { get; set; }
        public string BUSINESS_GROUP { get; set; }
        public string PRIMARY_PRODUCT { get; set; }
        public string ORDER_CREATED_BY { get; set; }
        public string ORDER_OWNER { get; set; }
        public string BACKLOG_STATUS { get; set; }
        public string DELV_BLK_TYPE { get; set; }
        public Nullable<int> ORDER_AGE { get; set; }
        public string Aging_Bucket { get; set; }
        public int SNI_AGE { get; set; }
        public string SNI_AGING_BUCKET { get; set; }
        public string SNI_CLOSURE_STATUS { get; set; }
        public string DB_CLOSURE_STATUS { get; set; }
        public double BACKLOG_AMT { get; set; }
        public string COMPLETE_DELIVERY_HEADER { get; set; }
        public string SOLD_TO_PARTY_NAME { get; set; }
        public string SHIP_TO_PARTY_NAME { get; set; }
        public string ZU_ACCOUNT_NAME { get; set; }
        public string FE_FE_DESC { get; set; }
        public string SRTATTR_AREA_MGR_NME { get; set; }
        public string SRTATTR_DISTRICT_MGR_NME { get; set; }
        public string PAYMENT_TERMS { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string SHIPPING_POINT { get; set; }
        public string DELIVERY_BLK_HDR_CD { get; set; }
        public string DELIVERY_BLK_HDR_DESC { get; set; }
        public string BILLING_BLOCK_CD { get; set; }
        public string BILLING_BLOCK_DESC { get; set; }
        public string NLHD_STATUS { get; set; }
        public Nullable<System.DateTime> COMMIT_DATE { get; set; }
        public string DELTA_LOAD_DATE_BUCKET { get; set; }
        public int SNI_CLOSURE_DAYS_DELTA { get; set; }
        public int DB_CLOSURE_DAYS_DELTA { get; set; }
        public Nullable<System.DateTime> ORDER_DT { get; set; }
        public Nullable<System.DateTime> CUSTOMER_REQ_GI_DATE { get; set; }
        public string EARLY_DEL_ACCEPTABLE { get; set; }
        public System.DateTime DELIVERY_BLOCK_CUT_OFF_DATE { get; set; }
        public Nullable<System.DateTime> EXPECTED_RELEASE_DATE { get; set; }
        public string REASON_CODE { get; set; }
        public string LATEST_COMMENT { get; set; }
        public string LATEST_COMMENT_BY { get; set; }
        public Nullable<System.DateTime> LATEST_COMMENT_DATE_TIME { get; set; }
        public string OVERALL_INSTALLATION_STATUS { get; set; }
        public string SOLD_TO_PARTY { get; set; }
        public string ZU_ACCOUNT_ID { get; set; }
        public string QUOTA_SF { get; set; }
    }
}
