//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Block_Details
    {
        public double SALES_ORDERNO { get; set; }
        public string BACKLOG_STATUS { get; set; }
        public Nullable<double> BACKLOG_AMT { get; set; }
        public string COMPLETE_DELIVERY_HEADER { get; set; }
        public string NLHD_STATUS { get; set; }
        public string DELIVERY_BLK_HDR_CD { get; set; }
        public string DELIVERY_BLK_HDR_DESC { get; set; }
        public string BILLING_BLOCK_CD { get; set; }
        public string BILLING_BLOCK_DESC { get; set; }
        public Nullable<System.DateTime> DELIVERY_BLOCK_CUT_OFF_DATE { get; set; }
        public Nullable<int> DELV_BLK_COUNT { get; set; }
        public Nullable<int> SAP_DELV_BLK_DAYS { get; set; }
        public Nullable<System.DateTime> DELV_BLK_LAST_APPLD_DT { get; set; }
        public Nullable<System.DateTime> DELV_BLK_REL_DT { get; set; }
        public string DLVY_DT_CHANGE_REASON { get; set; }
        public string DELV_BLK_TYPE { get; set; }
    }
}
