//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Archives
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public int ArchiveDate { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Report_Path { get; set; }
    }
}
