//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Followup_Summary
    {
        public int id { get; set; }
        public Nullable<int> TotalFollowups { get; set; }
        public Nullable<int> PassedDuedate { get; set; }
        public Nullable<int> DueToday { get; set; }
        public Nullable<int> ReassignedtoYou { get; set; }
        public Nullable<int> SystemGenerated { get; set; }
    }
}
