//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Items
    {
        public double SALES_ORDERNO { get; set; }
        public int LINE_ITEM { get; set; }
        public string MATERIAL_NO { get; set; }
        public string MATERIAL_DESC { get; set; }
        public string BUSINESS_GROUP { get; set; }
        public string DIVISION { get; set; }
        public string PRODUCT_LINE { get; set; }
        public string PL_DIVISION_DESC { get; set; }
        public string ITEM_BILLING_BLK_CD { get; set; }
        public string ITEM_BILLING_BLK_DESC { get; set; }
        public string DELV_BLK_LINE_CD { get; set; }
        public string DELV_BLK_LINE_DESC { get; set; }
        public string BACKLOG_STATUS { get; set; }
        public Nullable<double> BACKLOG_AMT { get; set; }
        public Nullable<System.DateTime> CUSTOMER_REQ_GI_DATE { get; set; }
        public Nullable<System.DateTime> TRIO_LOAD_DATE { get; set; }
        public Nullable<System.DateTime> COMMIT_DATE { get; set; }
        public string SERVICE_ORDER { get; set; }
        public string CRM_ITEM_STATUS { get; set; }
        public string CRM_INSTALL_START_DATE { get; set; }
        public string CRM_INSTALL_END_DATE { get; set; }
        public string CRM_INSTALL_COMPLETE_DATE { get; set; }
        public string FSE_NAME { get; set; }
    }
}
