//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Search
    {
        public Nullable<double> Sales_Order { get; set; }
        public string Found_in_Area { get; set; }
        public string Area_UI_Path { get; set; }
        public string Area_UI_Bucket { get; set; }
        public string Bucket_Security_On { get; set; }
        public string Current_Owner { get; set; }
    }
}
