//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Archival_Summary
    {
        public string Order_Owner { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<double> NetValue { get; set; }
    }
}
