//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_comments
    {
        public string Report { get; set; }
        public double Sales_Ord { get; set; }
        public string Material { get; set; }
        public string OrderOwner { get; set; }
        public string Reason_Code { get; set; }
        public string NextAction { get; set; }
        public Nullable<System.DateTime> Reviewdate { get; set; }
        public Nullable<System.DateTime> Cleardate { get; set; }
        public string Comment { get; set; }
        public string SignOff { get; set; }
        public Nullable<System.DateTime> snapshotdate { get; set; }
        public System.DateTime Comment_Date { get; set; }
        public string Commented_By { get; set; }
        public string SignOff_By { get; set; }
        public Nullable<System.DateTime> SignOff_Date { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> Approved_To_Date { get; set; }
        public Nullable<int> Line_Item { get; set; }
        public string Sales_Org { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<double> Net_Value { get; set; }
        public string Sold_To_Customer_Name { get; set; }
    }
}
