//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Unmapped_Users
    {
        public string REGION { get; set; }
        public string USERGROUP { get; set; }
        public Nullable<int> Order_Count { get; set; }
        public Nullable<double> Total_NV { get; set; }
        public Nullable<int> TotalUser { get; set; }
    }
}
