//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS
    {
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> TEAM_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string NTLOGIN { get; set; }
        public string COUNTRY { get; set; }
        public string FULLNAME { get; set; }
        public string SUPERREGION { get; set; }
        public string EMAIL { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> SUBSCRIPTION_ID { get; set; }
        public string PROFILE_PIC { get; set; }
    }
}
