//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Daily_Control_Reports_Summary
    {
        public string ReportName { get; set; }
        public string OrderOwner { get; set; }
        public Nullable<int> Pending_Comments { get; set; }
        public Nullable<int> Pending_Review { get; set; }
        public Nullable<int> Pending_Sign_Off { get; set; }
        public string Region { get; set; }
    }
}
