//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Partner_Details
    {
        public double SALES_ORDERNO { get; set; }
        public string SOLD_TO_PARTY { get; set; }
        public string SOLD_TO_PARTY_NAME { get; set; }
        public string SOLD_TO_COUNTRY { get; set; }
        public string SHIP_TO_PARTY_NAME { get; set; }
        public string SHIP_TO_PARTY { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string ZU_ACCOUNT_NAME { get; set; }
        public string ZU_COUNTRY { get; set; }
        public string QUOTA_SF { get; set; }
        public string FE_FE_DESC { get; set; }
        public string SRTATTR_AREA_MGR_NME { get; set; }
        public string SRTATTR_DISTRICT_MGR_NME { get; set; }
        public string ZU_ACCOUNT_ID { get; set; }
        public string EN_ACCOUNT_NAME { get; set; }
        public string EN_COUNTRY { get; set; }
    }
}
