//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Unmapped_Orders_By_Region_Function
    {
        public string REGION { get; set; }
        public string ORDER_CREATED_BY { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<double> Total_NV { get; set; }
    }
}
