//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OSBR_NOTIFICATIONS
    {
        public double SALES_DOC { get; set; }
        public int ITEM { get; set; }
        public string MATERIAL { get; set; }
        public string SORG { get; set; }
        public string SATY { get; set; }
        public string CREATED_BY { get; set; }
        public string CUSTOMER { get; set; }
        public string PL_DV { get; set; }
        public string ASSIGNED_ENGINEER_TEXT { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<int> QTY { get; set; }
        public string CURR { get; set; }
        public Nullable<double> TOT_LC_PRICE { get; set; }
        public Nullable<double> TOT_USD_PRICE { get; set; }
        public string DELIVERY_STATUS { get; set; }
        public string INVOICING_STATUS { get; set; }
        public string OWNER { get; set; }
        public string REGION { get; set; }
    }
}
