//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Country_Sorg_Orig
    {
        public int Id { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Country { get; set; }
        public string Sorg { get; set; }
        public string Region { get; set; }
    }
}
