//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_STR_Summary
    {
        public string Region { get; set; }
        public Nullable<double> TotalDBFocusList { get; set; }
        public Nullable<int> TotalOrders { get; set; }
        public string TargetPercentageQExit { get; set; }
        public Nullable<double> TargetReduction { get; set; }
        public Nullable<double> DBReleased { get; set; }
        public string PercentageReleased { get; set; }
        public Nullable<int> DBReleasedOrders { get; set; }
        public Nullable<double> DBOrders { get; set; }
        public Nullable<int> DBOrdersNo { get; set; }
        public Nullable<double> CancelledOrders { get; set; }
        public Nullable<int> CancelledOrdersNo { get; set; }
        public Nullable<double> AdjustedTotalDBFocusList { get; set; }
        public string AdjustedPerformance { get; set; }
        public Nullable<System.DateTime> LastRefreshDate { get; set; }
    }
}
