//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_WW_Blocked_Orders_Summary
    {
        public int Bucket_Rank { get; set; }
        public string Bucket { get; set; }
        public Nullable<double> AFO { get; set; }
        public Nullable<double> EMEAI { get; set; }
        public Nullable<double> JFO { get; set; }
        public Nullable<double> SAPK { get; set; }
        public Nullable<double> GCFO { get; set; }
        public Nullable<double> WW { get; set; }
        public string BucketName { get; set; }
    }
}
