//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Delivery_Info
    {
        public double SALES_ORDERNO { get; set; }
        public string COMPLETE_DELIVERY_HEADER { get; set; }
        public string NLHD_STATUS { get; set; }
        public Nullable<System.DateTime> CUSTOMER_REQ_GI_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_GI_DATE { get; set; }
        public string DELV_PRIO_CD_HDR { get; set; }
        public string DELV_PRIO_DESC_HDR { get; set; }
        public string EARLY_DEL_ACCEPTABLE { get; set; }
        public string SHIPPING_POINT { get; set; }
        public Nullable<System.DateTime> SHIPMENT_CUT_OFF_DATE { get; set; }
        public string SHIP_CONDTN_DESC { get; set; }
        public string SHIP_DT_CHANGE_REASON { get; set; }
        public string DLVY_DT_CHANGE_REASON { get; set; }
    }
}
