//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEAM_STRUCTURE
    {
        public int TEAM_ID { get; set; }
        public string TEAM_NAME { get; set; }
        public string SUPERVISOR { get; set; }
        public string BACKUP { get; set; }
        public Nullable<System.DateTime> BACKUPFROM { get; set; }
        public Nullable<System.DateTime> BACKUPTO { get; set; }
        public string BACKUP_COMMENTS { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    }
}
