//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Review_Reports
    {
        public string ReportName { get; set; }
        public string Status { get; set; }
        public string Frequency { get; set; }
        public string CustomFilter { get; set; }
        public string SAP_T_Code { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
    }
}
