//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Followups_History
    {
        public int HistoryID { get; set; }
        public int Followupid { get; set; }
        public Nullable<double> Sales_Order { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string BacklogStatus { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Re_Assigned_To { get; set; }
        public string Priority { get; set; }
        public string Modified_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Owner_Full_Name { get; set; }
    }
}
