//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SNI_Release_Projection
    {
        public double SALES_ORDERNO { get; set; }
        public string BUSINESS_SCENARIO { get; set; }
        public string BACKLOG_STATUS { get; set; }
        public string ORDER_CREATED_BY { get; set; }
        public string SALES_ORG { get; set; }
        public string REGION { get; set; }
        public string DIVISION { get; set; }
        public string BILLING_BLOCK_CD { get; set; }
        public string BILLING_BLOCK_DESC { get; set; }
        public string DELIVERY_BLK_HDR_DESC { get; set; }
        public Nullable<System.DateTime> Frcst_EstLoadDate { get; set; }
        public Nullable<System.DateTime> Feedback { get; set; }
        public string Feedback_MonthName { get; set; }
        public Nullable<int> BB_CycleTimeTarget { get; set; }
        public Nullable<System.DateTime> Feedback_Calc_Est_Invoice_dt { get; set; }
        public string Feedback_Calc_Est_Invoice_dt_Month { get; set; }
        public Nullable<System.DateTime> Est_InvoiceDate { get; set; }
        public string Est_MonthName { get; set; }
        public double BAcklog { get; set; }
        public string PRIMARY_PRODUCT { get; set; }
        public string TEAM_NAME { get; set; }
    }
}
