//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER_COMMENT_VIEW
    {
        public double SALES_ORDERNO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string SALES_ORG { get; set; }
        public string ORDER_OWNER { get; set; }
        public double BACKLOG_AMT { get; set; }
        public string SOLD_TO_PARTY_NAME { get; set; }
        public Nullable<System.DateTime> EXPECTED_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> REVIEW_DATE { get; set; }
        public string REASON_CODE { get; set; }
        public string LATEST_COMMENT { get; set; }
        public Nullable<System.DateTime> COMMENTED_DATE { get; set; }
        public string COMMENTED_BY { get; set; }
        public string REGION { get; set; }
        public Nullable<System.DateTime> ORDER_DT { get; set; }
        public int ORDER_AGE { get; set; }
        public Nullable<System.DateTime> APPROVED_TO_DATE { get; set; }
        public Nullable<System.DateTime> SNAPSHOT_DATE { get; set; }
        public Nullable<System.DateTime> CUSTOMER_REQ_GI_DATE { get; set; }
        public int CRDD_Age { get; set; }
        public string FE_FE_DESC { get; set; }
        public string ReportName { get; set; }
    }
}
