//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Header_Details
    {
        public double SALES_ORDERNO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string ORDER_CREATED_BY { get; set; }
        public string ORDER_OWNER { get; set; }
        public string REGION { get; set; }
        public string PRIMARY_PRODUCT { get; set; }
        public Nullable<int> ORDER_AGE { get; set; }
        public string Aging_Bucket { get; set; }
        public string BACKLOG_STATUS { get; set; }
        public Nullable<double> BACKLOG_AMT { get; set; }
        public string PAYMENT_TERMS { get; set; }
        public string PAYMENT_TERMS_DESC { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string COMPLETE_DELIVERY_HEADER { get; set; }
        public Nullable<System.DateTime> ORDER_DT { get; set; }
        public Nullable<int> DB_CLOSURE_DAYS_DELTA { get; set; }
        public string DELTA_LOAD_DATE_BUCKET { get; set; }
        public Nullable<int> SNI_CLOSURE_DAYS_DELTA { get; set; }
        public Nullable<int> SNI_AGE { get; set; }
        public string SNI_AGING_BUCKET { get; set; }
        public string OVERALL_INSTALLATION_STATUS { get; set; }
    }
}
