//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order_Action_Owner
    {
        public double SALES_ORDERNO { get; set; }
        public string Default_Owner { get; set; }
        public string Current_Owner { get; set; }
        public string Current_Owner_SAPName { get; set; }
        public string Ownership_Type { get; set; }
        public Nullable<System.DateTime> Ownership_From { get; set; }
        public Nullable<System.DateTime> Ownership_To { get; set; }
        public string Assigned_By { get; set; }
        public System.DateTime Assigned_On { get; set; }
    }
}
