//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Backlog_Summary
    {
        public System.DateTime SnapshotDate { get; set; }
        public string SAP_User { get; set; }
        public string Region { get; set; }
        public string Sorg { get; set; }
        public Nullable<double> Total_SNI { get; set; }
        public Nullable<int> Total_SNI_Count { get; set; }
        public Nullable<double> Total_SNI_Aged { get; set; }
        public Nullable<int> Total_SNI_Aged_Count { get; set; }
        public Nullable<double> Total_SNI_Expected_Release_Today { get; set; }
        public Nullable<int> Total_SNI_Expected_Release_Today_Count { get; set; }
        public Nullable<double> Total_SNI_Expected_Released_Passed { get; set; }
        public Nullable<int> Total_SNI_Expected_Released_Passed_Count { get; set; }
        public Nullable<double> Total_SNI_No_Expected_Release_Date { get; set; }
        public Nullable<int> Total_SNI_No_Expected_Release_Date_Count { get; set; }
        public Nullable<double> Total_SNI_MF_Invoicing_Errors { get; set; }
        public Nullable<int> Total_SNI_MF_Invoicing_Errors_Count { get; set; }
        public Nullable<double> Total_DB { get; set; }
        public Nullable<int> Total_DB_Count { get; set; }
        public Nullable<double> Total_DB_greater_90_Days { get; set; }
        public Nullable<int> Total_DB_greater_90_Days_Count { get; set; }
        public Nullable<double> Total_DB_Expected_Released_Passed { get; set; }
        public Nullable<int> Total_DB_Expected_Released_Passed_Count { get; set; }
        public Nullable<double> Total_DB_Overdue { get; set; }
        public Nullable<int> Total_DB_Overdue_Count { get; set; }
        public Nullable<double> Total_DB_Overdue_14_Days { get; set; }
        public Nullable<int> Total_DB_Overdue_14_Days_Count { get; set; }
        public Nullable<double> Total_DB_SppedtoRevenue { get; set; }
        public Nullable<int> Total_DB_SppedtoRevenue_Count { get; set; }
        public Nullable<double> Total_Unblocked_Orders { get; set; }
        public Nullable<int> Total_Unblocked_Orders_Count { get; set; }
        public Nullable<double> Total_Unblocked_Overdue { get; set; }
        public Nullable<int> Total_Unblocked_Overdue_Count { get; set; }
        public Nullable<double> Total_OSBR_Notification { get; set; }
        public Nullable<int> Total_OSBR_Notification_Count { get; set; }
    }
}
