//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_Repricing_Ordes
    {
        public Nullable<double> Document { get; set; }
        public Nullable<double> Item { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public Nullable<System.DateTime> Pricing_dt { get; set; }
        public string Material { get; set; }
        public string Pricing_Month_Year { get; set; }
        public string Created_On_Month_Year { get; set; }
        public bool FLAG { get; set; }
    }
}
