//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BCR_SignOff_Summary
    {
        public string Region { get; set; }
        public string Report { get; set; }
        public Nullable<int> Commented_Sign_Off { get; set; }
        public Nullable<System.DateTime> snapshotdateFrom { get; set; }
        public Nullable<System.DateTime> snapshotdateTo { get; set; }
    }
}
