//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ControlReports
    {
        public double SALES_ORDERNO { get; set; }
        public string CUSTOMER_PO_NO { get; set; }
        public string SALES_ORG { get; set; }
        public string ORDER_OWNER { get; set; }
        public string ORDER_CREATED_BY { get; set; }
        public Nullable<double> BACKLOG_AMT { get; set; }
        public string SOLD_TO_PARTY_NAME { get; set; }
        public string EXPECTED_RELEASE_DATE { get; set; }
        public string REVIEW_DATE { get; set; }
        public string REASON_CODE { get; set; }
        public string LATEST_COMMENT { get; set; }
        public string COMMENTED_DATE { get; set; }
        public string COMMENTED_BY { get; set; }
        public string REGION { get; set; }
    }
}
