//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STR_Summary
    {
        public string Region { get; set; }
        public string TotalDBFocusList { get; set; }
        public string TotalOrders { get; set; }
        public string TargetPercentageQExit { get; set; }
        public string TargetReduction { get; set; }
        public string DBReleased { get; set; }
        public string PercentageReleased { get; set; }
        public string DBReleasedOrders { get; set; }
        public string DBOrders { get; set; }
        public string DBOrdersNo { get; set; }
        public string CancelledOrders { get; set; }
        public string CancelledOrdersNo { get; set; }
        public string AdjustedTotalDBFocusList { get; set; }
    }
}
