//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SNI_Mater_Focus_Main_Orders
    {
        public double SALES_ORDERNO { get; set; }
        public Nullable<double> NV_Sum { get; set; }
    }
}
