//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USERS
    {
        public int USER_ID { get; set; }
        public string ROLE_DESC { get; set; }
        public string TEAM_NAME { get; set; }
        public string Manager { get; set; }
        public string NTLOGIN { get; set; }
        public string COUNTRY { get; set; }
        public string FULLNAME { get; set; }
        public string SUPERREGION { get; set; }
        public string EMAIL { get; set; }
        public string ACTIVE { get; set; }
        public string PROFILE_PIC { get; set; }
        public string SAP_User_Name { get; set; }
    }
}
